solana:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: vna27887.us-east-1
      role: INTERNAL_DEV
      user: jessica@flipsidecrypto.com
      authenticator: externalbrowser
      region: us-east-1
      database: SOLANA_DEV
      warehouse: DBT_EMERGENCY
      schema: silver
      threads: 12
      client_session_keep_alive: False
      query_tag: dbt_JESSICA_dev
  config:
    send_anonymous_usage_stats: False