name: dbt_run_deploy_udfs_and_sps
run-name: dbt_run_deploy_udfs_and_sps

on:
  push:
    branches:
      - main  
    paths:
      - 'macros/**'
    
env:
  DBT_PROFILES_DIR: "${{ secrets.DBT_PROFILES_DIR }}"

  ACCOUNT: "${{ secrets.ACCOUNT }}"
  ROLE: "${{ secrets.ROLE }}"
  USER: "${{ secrets.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ secrets.REGION }}"
  DATABASE: "${{ secrets.DATABASE }}"
  WAREHOUSE: "${{ secrets.WAREHOUSE }}"
  SCHEMA: "${{ secrets.SCHEMA }}"

concurrency:
  group: ${{ github.workflow }}

jobs:
  run_dbt_jobs:
    runs-on: ubuntu-latest
    environment: 
      name: workflow_prod

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: install dependencies
        run: |
          pip3 install dbt-snowflake==${{ secrets.DBT_VERSION }} cli_passthrough requests click
          dbt deps

      - name: Run DBT Jobs
        run: |
          dbt run --vars '{"UPDATE_UDFS_AND_SPS": True}' -s models/bronze/bronze__blocks.sql
          
