name: dbt_run_scheduled_daily
run-name: dbt_run_scheduled_daily

on:
  schedule:
    # Runs 00:35 daily (see https://crontab.guru)
    - cron: '35 0 * * *'
    
env:
  DBT_PROFILES_DIR: "${{ secrets.DBT_PROFILES_DIR }}"

  ACCOUNT: "${{ secrets.ACCOUNT }}"
  ROLE: "${{ secrets.ROLE }}"
  USER: "${{ secrets.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ secrets.REGION }}"
  DATABASE: "${{ secrets.DATABASE }}"
  WAREHOUSE: "${{ secrets.WAREHOUSE }}"
  SCHEMA: "${{ secrets.SCHEMA }}"

concurrency:
  group: ${{ github.workflow }}

jobs:
  run_dbt_jobs:
    runs-on: ubuntu-latest
    environment: 
      name: workflow_prod

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: install dependencies
        run: |
          pip3 install dbt-snowflake==${{ secrets.DBT_VERSION }} cli_passthrough requests click
          dbt deps
      - name: Run DBT Jobs
        run: |
          dbt run -s models/silver/silver__daily_signers.sql+
          dbt run -s models/silver/nfts/silver__nft_mints.sql --full-refresh
          dbt run-operation run_sp_snapshot_get_validators_app_data
          dbt run-operation run_sp_snapshot_get_vote_accounts
          dbt run-operation run_sp_snapshot_get_stake_accounts
          dbt run-operation run_sp_snapshot_get_vote_program_accounts
          dbt run-operation get_block_production
          dbt run -s models/bronze/bronze__validators_app_api.sql models/bronze/bronze__vote_accounts.sql models/bronze/bronze__stake_program_accounts.sql models/bronze/bronze__vote_accounts_extended_stats.sql
          dbt run -s models/silver/validator/silver__snapshot_stake_accounts.sql models/silver/validator/silver__snapshot_validators_app_data.sql models/silver/validator/silver__snapshot_vote_accounts.sql models/silver/validator/silver__snapshot_vote_accounts_extended_stats.sql models/silver/validator/silver__snapshot_block_production.sql

