name: scheduled_incremental_dbt_run
run-name: scheduled_incremental_dbt_run

on:
  push:
    branches:
      - main
  schedule:
    # Runs "every hour" (see https://crontab.guru)
    - cron: '0 */1 * * *'
    
env:
  DBT_PROFILES_DIR: ./

  ACCOUNT: "${{ secrets.ACCOUNT }}"
  ROLE: "${{ secrets.ROLE }}"
  USER: "${{ secrets.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ secrets.REGION }}"
  DATABASE_DEV: "${{ secrets.DATABASE_DEV }}"
  DATABASE_PROD: "${{ secrets.DATABASE_PROD }}"
  WAREHOUSE_DEV: "${{ secrets.WAREHOUSE_DEV }}"
  WAREHOUSE_PROD: "${{ secrets.WAREHOUSE_PROD }}"
  SCHEMA: "${{ secrets.SCHEMA }}"


jobs:
  called_workflow_template:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/run_chain_template.yml@main
    with:
      dbt_command: "dbt run-operation run_sp_refresh_external_tables_full -t prod"
    secrets: inherit
  called_workflow_template2:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/run_chain_template.yml@main
    with:
      dbt_command: "dbt run -m ./models/bronze -t prod"
    secrets: inherit