name: adhoc_dbt_run
run-name: call_workflow_template

on:
  workflow_dispatch:
    inputs:
      dbt_command:
        type: string
        description: 'DBT Run Command'
        required: true
    
env:
  DBT_PROFILES_DIR: ./

  ACCOUNT: "${{ secrets.ACCOUNT }}"
  ROLE: "${{ secrets.ROLE }}"
  USER: "${{ secrets.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ secrets.REGION }}"
  DATABASE_DEV: "${{ secrets.DATABASE_DEV }}"
  DATABASE_PROD: "${{ secrets.DATABASE_PROD }}"
  WAREHOUSE_DEV: "${{ secrets.WAREHOUSE_DEV }}"
  WAREHOUSE_PROD: "${{ secrets.WAREHOUSE_PROD }}"
  SCHEMA: "${{ secrets.SCHEMA }}"
  QUERY_TAG: "solana_dbt_adhoc"


jobs:
  called_workflow_template:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/run_chain_template.yml@main
    with:
      dbt_command: ${{ inputs.dbt_command }}
    secrets: inherit # pass all secrets
  