name: dbt_test_scheduled
run-name: dbt_test_scheduled

on:
  workflow_dispatch:
  schedule:
    # Run at 9am UTC daily (see https://crontab.guru)
    - cron: '0 9 * * *'
    
env:
  DBT_PROFILES_DIR: ./

  ACCOUNT: "${{ secrets.ACCOUNT }}"
  ROLE: "${{ secrets.ROLE }}"
  USER: "${{ secrets.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ secrets.REGION }}"
  DATABASE: "${{ secrets.DATABASE }}"
  WAREHOUSE: "${{ secrets.WAREHOUSE }}"
  SCHEMA: "${{ secrets.SCHEMA }}"


jobs:
  run_dbt_jobs:
    runs-on: ubuntu-latest
    environment: 
      name: workflow_prod

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: install dependencies
        run: |
          pip3 install dbt-snowflake==1.3.0 cli_passthrough requests click
          dbt deps
      - name: Run DBT Jobs
        run: |
          dbt test -s ./models