version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: solana_blocks
      - name: solana_txs
  - name: crosschain
    database: flipside_prod_db
    schema: silver_crosschain
    tables:
      - name: address_labels
  - name: shared
    database: flipside_prod_db
    schema: silver
    tables:
      - name: prices_v2
  - name: legacy_bronze
    database: flipside_prod_db
    schema: bronze
    tables: 
      - name: prod_nft_metadata_uploads_1828572827
  - name: solana_external
    schema: bronze
    loader: S3
    tables:
      - name: decoded_instructions_data_api
        description: "External table of solana decoded instructions data"
        external:
          location: "@solana.bronze.analytics_external_tables/{{target.database}}/DECODED_INSTRUCTIONS_DATA_API"
          file_format: "( type = json, strip_outer_array = TRUE )"
          auto_refresh: true
        columns:
          - name: tx_id
            data_type: string
            description: ""
          - name: event_index
            data_type: number
            description: ""
          - name: program_id
            data_type: string
            description: ""
          - name: instruction_type
            data_type: string
            description: ""
          - name: data
            data_type: variant
            description: ""
      - name: validator_metadata_api
        description: "External table of solana validator metadata"
        external:
          location: "@solana.bronze.analytics_external_tables/{{target.database}}/VALIDATOR_METADATA_API"
          file_format: "( type = json, strip_outer_array = TRUE )"
          auto_refresh: true
      - name: stake_account_tx_ids_api
        description: "External table of solana stake account tx ids"
        external:
          location: "@solana.bronze.analytics_external_tables/{{target.database}}/STAKE_ACCOUNT_TX_IDS_API"
          file_format: "( type = json, strip_outer_array = TRUE )"
          auto_refresh: true
        columns:
          - name: account
            data_type: string
          - name: slot
            data_type: number
          - name: blockTime
            data_type: number
          - name: signature
            data_type: string
  