version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: solana_blocks
      - name: solana_txs
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'SOLANA' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: address_labels
      - name: dim_date_hours
  - name: crosschain_public
    database: "{{ 'crosschain' if target.database == 'SOLANA' else 'crosschain_dev' }}"
    schema: bronze_public
    tables:
      - name: user_idls
  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database == 'SOLANA' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: asset_metadata_coin_market_cap
      - name: asset_metadata_coin_gecko
      - name: hourly_prices_coin_market_cap
      - name: hourly_prices_coin_gecko
      - name: coin_market_cap_cryptocurrency_info
      - name: apis_keys
      - name: number_sequence

  - name: shared
    database: flipside_prod_db
    schema: silver
    tables:
      - name: prices_v2
  - name: legacy_bronze
    database: flipside_prod_db
    schema: bronze
    tables: 
      - name: prod_nft_metadata_uploads_1828572827
  - name: bronze_streamline
    database: streamline
    schema: solana
    tables:
      - name: decode_instructions_idls
      - name: decoded_instructions_data_api
      - name: validator_metadata_api
      - name: stake_account_tx_ids_api
      - name: txs_api
      - name: blocks_api
      - name: block_rewards_api
      - name: block_txs_api
      - name: validator_vote_accounts
      - name: validators_app_list_api
      - name: stake_program_accounts
      - name: validator_vote_program_accounts
      - name: program_parser
  - name: bronze_api
    schema: bronze_api
    tables:
      - name: solscan_token_list
      - name: token_metadata
      - name: block_production
  - name: solana_silver
    schema: silver
    tables:
      - name: nft_sales_solport
      - name: nft_sales_magic_eden_v1
  - name: solana_streamline
    schema: streamline
    tables:
      - name: complete_block_txs
  - name: bronze
    schema: bronze
    tables:
      - name: decoded_instructions
      - name: block_production
      - name: historical_vote_account_data
      - name: historical_validator_app_data
      - name: historical_stake_account_data
