version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: solana_blocks
      - name: solana_txs
  - name: crosschain
    database: crosschain
    schema: core
    tables:
      - name: address_labels
  - name: shared
    database: flipside_prod_db
    schema: silver
    tables:
      - name: prices_v2
  - name: legacy_bronze
    database: flipside_prod_db
    schema: bronze
    tables: 
      - name: prod_nft_metadata_uploads_1828572827
  - name: bronze_streamline
    database: streamline
    schema: solana
    tables:
      - name: decoded_instructions_data_api
      - name: validator_metadata_api
      - name: stake_account_tx_ids_api
      - name: txs_api
      - name: blocks_api
      - name: block_rewards_api
      - name: block_txs_api