version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: solana_blocks
      - name: solana_txs
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'SOLANA' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_labels
      - name: dim_date_hours
  - name: crosschain_public
    database: "{{ 'crosschain' if target.database == 'SOLANA' else 'crosschain_dev' }}"
    schema: bronze_public
    tables:
      - name: user_idls
  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database == 'SOLANA' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: apis_keys
      - name: number_sequence
      - name: labels_combined
      - name: complete_token_asset_metadata
      - name: complete_token_prices
      - name: complete_provider_asset_metadata
      - name: complete_provider_prices
      - name: complete_native_asset_metadata
      - name: complete_native_prices
  - name: crosschain_bronze
    database: "{{ 'crosschain' if target.database == 'SOLANA' else 'crosschain_dev' }}"
    schema: bronze
    tables:
      - name: legacy_prices
  - name: bronze_streamline
    database: streamline
    schema: "{{ 'solana' if target.database == 'SOLANA' else 'solana_dev' }}"
    tables:
      - name: decode_instructions_idls
      - name: decoded_instructions_data_api
      - name: validator_metadata_api
      - name: stake_account_tx_ids_api
      - name: txs_api
      - name: blocks_api
      - name: block_rewards_api
      - name: block_txs_api
      - name: validator_vote_accounts
      - name: validators_app_list_api
      - name: stake_program_accounts
      - name: validator_vote_program_accounts
      - name: program_parser
      - name: decoded_instructions_2
      - name: decoded_logs
      - name: stake_program_accounts_2
      - name: block_rewards_2
      - name: helius_nft_metadata
      - name: blocks_2
      - name: validator_vote_accounts_2
      - name: validator_vote_program_accounts_2
      - name: validator_metadata_2
      - name: validators_list_2
      - name: solscan_blocks_2
      - name: solscan_token_list
      - name: decoded_instructions_3
      - name: decoded_logs_2
      - name: block_txs_2
      - name: helius_blocks
      - name: block_txs_index_backfill
  - name: bronze_api
    schema: bronze_api
    tables:
      - name: solscan_token_list
      - name: token_metadata
      - name: block_production
  - name: solana_silver
    schema: silver
    tables:
      - name: nft_sales_solport
      - name: nft_sales_magic_eden_v1
      - name: nft_sales_opensea
      - name: nft_sales_yawww
      - name: nft_bids_yawww
      - name: gauges_votes_marinade
      - name: gauges_creates_marinade
      - name: nft_sales_coral_cube
      - name: swaps_intermediate_jupiterv5_1
      - name: swaps_intermediate_jupiterv5_2
      - name: rewards_rent
      - name: rewards_fee
      - name: rewards_voting
      - name: rewards_staking
      - name: stake_pool_actions_eversol
      - name: nft_sales_smb
      - name: nft_mint_price_other
      - name: nft_metadata
      - name: proposal_votes_marinade
      - name: stake_pool_actions_socean
      - name: _blocks_tx_count
      - name: nft_sales_solsniper_v1_events
      - name: swaps_intermediate_jupiterv6
      - name: nft_sales_amm_sell
      - name: nft_sales_hyperspace
      - name: stake_pool_actions_lido
      - name: nft_sales_hadeswap
      - name: swaps_intermediate_jupiterv4
      - name: nft_collection
      - name: burns_orca_non_whirlpool
      - name: mints_orca_non_whirlpool
      - name: pool_transfers_orca_non_whirlpool
      - name: initialization_pools_orca
      - name: nft_sales_magic_eden_v2
      - name: snapshot_block_production
      - name: bridge_mayan_transfers
  - name: solana_streamline
    database: solana
    schema: streamline
    tables:
      - name: complete_block_txs
      - name: complete_block_rewards
      - name: complete_blocks
      - name: complete_block_txs_2
  - name: bronze
    schema: bronze
    tables:
      - name: decoded_instructions
      - name: block_production
      - name: historical_vote_account_data
      - name: historical_validator_app_data
      - name: historical_stake_account_data
  - name: bronze_api_prod
    database: solana
    schema: bronze_api
    tables:
      - name: parse_compressed_nft_mints_requests
  - name: github_actions
    database: solana
    schema: github_actions
    tables:
      - name: workflows
  - name: solana_test_silver
    schema: test_silver 
    tables: 
      - name: transactions_and_votes_missing_7_days
      - name: rewards_gaps